# Putting it all together

In [1]:
from transformers import AutoTokenizer

checkpoint = "distilbert-base-uncased-finetuned-sst-2-english"
tokenizer = AutoTokenizer.from_pretrained(checkpoint)

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_token.py:88: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/629 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

In [2]:
sequence = 'Never forget what you are. Cause Rest of the world will not'

Method can Tokenize Single sequence

In [3]:
model_input = tokenizer(sequence)
print(model_input)

{'input_ids': [101, 2196, 5293, 2054, 2017, 2024, 1012, 3426, 2717, 1997, 1996, 2088, 2097, 2025, 102], 'attention_mask': [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]}


Also Multiple Sequences

In [5]:
seq_list = [sequence, 'Wear it like an Armour and it can never again be used to hurt you', 'Remeber it well']
model_input = tokenizer(seq_list)
print(model_input)

{'input_ids': [[101, 2196, 5293, 2054, 2017, 2024, 1012, 3426, 2717, 1997, 1996, 2088, 2097, 2025, 102], [101, 4929, 2009, 2066, 2019, 12371, 1998, 2009, 2064, 2196, 2153, 2022, 2109, 2000, 3480, 2017, 102], [101, 2128, 4168, 5677, 2009, 2092, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}


Add Padding

In [7]:
# Padding upto maximum sequence length
model_input = tokenizer(seq_list, padding = 'longest')
print(model_input)

{'input_ids': [[101, 2196, 5293, 2054, 2017, 2024, 1012, 3426, 2717, 1997, 1996, 2088, 2097, 2025, 102, 0, 0], [101, 4929, 2009, 2066, 2019, 12371, 1998, 2009, 2064, 2196, 2153, 2022, 2109, 2000, 3480, 2017, 102], [101, 2128, 4168, 5677, 2009, 2092, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]}


In [13]:
# Padding upto model's maximum length (512 for BERT or DistilBERT)
model_input = tokenizer(seq_list, padding = 'max_length')
print(model_input)

{'input_ids': [[101, 2196, 5293, 2054, 2017, 2024, 1012, 3426, 2717, 1997, 1996, 2088, 2097, 2025, 102, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [15]:
# Pad by specified maximum length
model_input = tokenizer(seq_list, padding = 'max_length', max_length = 8)
print(model_input)

{'input_ids': [[101, 2196, 5293, 2054, 2017, 2024, 1012, 3426, 2717, 1997, 1996, 2088, 2097, 2025, 102], [101, 4929, 2009, 2066, 2019, 12371, 1998, 2009, 2064, 2196, 2153, 2022, 2109, 2000, 3480, 2017, 102], [101, 2128, 4168, 5677, 2009, 2092, 102, 0]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 0]]}


Truncation

In [18]:
# Trucate sequecne more than max model length (512 for BERT and DistilBERT)
model_input = tokenizer(seq_list, truncation = True)
print(model_input)

{'input_ids': [[101, 2196, 5293, 2054, 2017, 2024, 1012, 3426, 2717, 1997, 1996, 2088, 2097, 2025, 102], [101, 4929, 2009, 2066, 2019, 12371, 1998, 2009, 2064, 2196, 2153, 2022, 2109, 2000, 3480, 2017, 102], [101, 2128, 4168, 5677, 2009, 2092, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}


In [19]:
# Trucate sequecne more than specified max model length
model_input = tokenizer(seq_list, truncation = True, max_length = 8)
print(model_input)

{'input_ids': [[101, 2196, 5293, 2054, 2017, 2024, 1012, 102], [101, 4929, 2009, 2066, 2019, 12371, 1998, 102], [101, 2128, 4168, 5677, 2009, 2092, 102]], 'attention_mask': [[1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1, 1], [1, 1, 1, 1, 1, 1, 1]]}


Get Tensors in different formats

In [27]:
# TensorFlow Tensor
model_input = tokenizer(seq_list, padding = True, return_tensors= 'tf')
print(model_input)

{'input_ids': <tf.Tensor: shape=(3, 17), dtype=int32, numpy=
array([[  101,  2196,  5293,  2054,  2017,  2024,  1012,  3426,  2717,
         1997,  1996,  2088,  2097,  2025,   102,     0,     0],
       [  101,  4929,  2009,  2066,  2019, 12371,  1998,  2009,  2064,
         2196,  2153,  2022,  2109,  2000,  3480,  2017,   102],
       [  101,  2128,  4168,  5677,  2009,  2092,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]],
      dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(3, 17), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]], dtype=int32)>}


In [29]:
# PyTorch Tensor
model_input=  tokenizer(seq_list, padding= True, return_tensors = 'pt')
print(model_input)

{'input_ids': tensor([[  101,  2196,  5293,  2054,  2017,  2024,  1012,  3426,  2717,  1997,
          1996,  2088,  2097,  2025,   102,     0,     0],
        [  101,  4929,  2009,  2066,  2019, 12371,  1998,  2009,  2064,  2196,
          2153,  2022,  2109,  2000,  3480,  2017,   102],
        [  101,  2128,  4168,  5677,  2009,  2092,   102,     0,     0,     0,
             0,     0,     0,     0,     0,     0,     0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
        [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}


In [30]:
# numpy array
model_input = tokenizer(seq_list, padding = True, return_tensors='np')
print(model_input)

{'input_ids': array([[  101,  2196,  5293,  2054,  2017,  2024,  1012,  3426,  2717,
         1997,  1996,  2088,  2097,  2025,   102,     0,     0],
       [  101,  4929,  2009,  2066,  2019, 12371,  1998,  2009,  2064,
         2196,  2153,  2022,  2109,  2000,  3480,  2017,   102],
       [  101,  2128,  4168,  5677,  2009,  2092,   102,     0,     0,
            0,     0,     0,     0,     0,     0,     0,     0]]), 'attention_mask': array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])}


Special Tokens

In [33]:
decoded_seq = tokenizer.decode(model_input['input_ids'][0])
print(decoded_seq)

[CLS] never forget what you are. cause rest of the world will not [SEP] [PAD] [PAD]


Can see that there are special tokens added for Classification, Seperation and Padding

Wrap UP

In [37]:
import tensorflow as tf
from transformers import AutoTokenizer, TFAutoModelForSequenceClassification
checkpoint = checkpoint
seq_list = seq_list
tokenizer = AutoTokenizer.from_pretrained(checkpoint)
model = TFAutoModelForSequenceClassification.from_pretrained(checkpoint)

tokens = tokenizer(seq_list, padding = True, truncation= True, return_tensors= 'tf')
output = model(**tokens)
print(output)

All PyTorch model weights were used when initializing TFDistilBertForSequenceClassification.

All the weights of TFDistilBertForSequenceClassification were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFDistilBertForSequenceClassification for predictions without further training.


TFSequenceClassifierOutput(loss=None, logits=<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-1.4141196,  1.39453  ],
       [-1.4846175,  1.5307894],
       [-3.9178991,  4.149091 ]], dtype=float32)>, hidden_states=None, attentions=None)
